version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./Game.Client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.Server
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000